### PR TITLE
shs-4926: component field naming and ordering

### PR DESCRIPTION
**Pull request by ryanhagerty**
## Summary
Changes the naming and ordering of several components' fields.

## Steps to Test
1. The list of requests was quite extensive, so for testing purposes I suggest going through the ticket (https://app.clickup.com/t/36718269/SHS-4926) and checking there.

## Notes
There were some asks that didn't exist:
* For the Collection field options there were a couple renames such as `Well limited-width → Limited Width`. This does not exist so it wasn't changed.
* For the Photo Album (`admin/structure/paragraphs_type/stanford_gallery`), tabs are under `Behaviors`. I removed the tabs like the ticket instructed, but that involves removing some fields as well because it's all under `Behaviors`. If we want to keep those, we'll have to recreate them as fields.
* Everything in the ticket was addressed as if it were its own component, however many components are made of referenced paragraphs (Hero Layered Slider is made of Hero Overlay paragraphs, etc.). I changed the base component as I believe that was the spirit of the ticket.

### CODE REVIEW

**Comment by cienvaras** [comment]
@ryanhagerty Everything seems to work as expected except the following:

- Callout Box
  - Can we add help text at the paragraph level, "A Callout Box needs to be immediately followed by a Text Area component."

I noticed you added the text as the Callout box paragraph description, however it's not visible as helptext when adding a paragraph in a page:

---

- Collection
  - Field options
    - Well limited-width → Limited Width
    - Well full-width → Full Width

I see your comment in the PR description about not finding the field, but it's present when I add a Collection paragraph in the hs-colorful site:

Screenshot 2023-05-22 at 16 55 08

Maybe the field is overriden?

---

- Photo Album
  - Order of components
    - Remove the tabs for Content and Style

I see your comment on the need to recreate the fields in the style tab. Tagging @callinmullaney so he can give us some input on the best way to proceed.

**Comment by ryanhagerty** [comment]
@cienvaras 

Thanks for the review and catching that field I couldn't find.

I addressed the collection field labels and added help text to the Callout paragraph. Because there's no top level description, I added it to the top field (body).

**Review by callinmullaney — CHANGES_REQUESTED** [review]
@ryanhagerty @cienvaras - I dove into this one a bit and think I found a path forward but I think we'll need some backend work from Andres or Hector in order to consider this "complete". 

Ryan can you implement the follow:
1. Restore the Photo Gallery Behavior setting you're currently disabling in this PR
2. Add a new field to the Photo Gallery paragraph with the following details:
    - field machine name = `field_photoalbum_style`
    - Label = Style
    - Field Type = Display Mode Select
    - Label for Default value = Grid
    - Label for Gallery Slideshow value = Slideshow
    - Set as "Required" with the default value set to "Grid"
    - Limit to only 1 value
    - Remove the following block of code (line 11 through 18) https://github.com/SU-HSDO/suhumsci/blob/develop/docroot/modules/humsci/hs_paragraph_types/hs_paragraph_types.module#L11 
3. Hide the tabs from the form display temporarily. You can do this via CSS `.paragraph-type--stanford-gallery .hs-paragraphs-tabs tabs { display: none; }` that should only be present for the admin theme. Otherwise, if you're feel ambitious you can do a `hook_field_widget_paragraphs_form_alter(&$element, &$form_state, $context)` and `unset` these tabs. Likely found in `$element`
    - The idea here is the current implementation is still attached to existing paragraphs so we can extract the value and transfer it to the new field (see below). Then, at some point after this is deployed, we can safely disable this behavior and preserve all the existing functionality.

Remaining backend task:
- Write an update hook to set the value of the new `field_photoalbum_style` field with the value stored in `$entity->getBehaviorSetting('image_gallery')` for all existing photo album paragraphs

**Comment by ryanhagerty** [comment]
FE portion of Callin's request is complete with latest commit

**Comment by cienvaras** [comment]
@callinmullaney Update hook done, ready for review.

**Review by callinmullaney — APPROVED** [review]
Everything here looks good to me!

**Pull request merged**
