### PR TITLE
SHS-4966: Fix smart link popup/modal sizing and orientation issue

### PR DESCRIPTION
**Pull request by cienvaras**
# READY FOR REVIEW

## Summary
- Limit size of autocomplete options in the ckeditor link dialog

## Urgency
- normal

## Steps to Test
1. Create a flexible page. Add some text in the main region text area
2. Select some text and add a link. Start typing some text in the Link URL fix and wait for the autocomplete options to appear. Confirm that the dialog is always smaller than the browser window.

**NOTE:** This PR partially fixes [the ticket](https://app.clickup.com/t/36718269/SHS-4966). The second acceptance criteria (prevent the dialog to jump when the user scrolls) is not possible without modifying the linkit module (and possible ckeditor itself), because the position adjustment on scroll is the default behavior of the link dialog.

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

### CODE REVIEW

**Review by callinmullaney — CHANGES_REQUESTED** [review]
@cienvaras The changes you made here definitely make this popup more usable and prevent the situation Joey pointed out where it essentially takes over the entire screen making things unusable. I also agree that the "jumping around of the popup when scrolling" isn't really possible to fix without significant development work to contrib back to the plugin or overwrite it's positioning behavior. I actually think it's attempts to keep the popup window within browser window when scrolling/resizing is actually a feature.

That being said, I think there is a little bit more we can add here to improve things. Take this scenario: If I have my browser window open to a small desktop size or lower and search for a URL I start seeing the following:
Screenshot from 2023-07-07 13-12-43

I think this can be remedied by adding a reasonable "max-width" to the markup highlighted in my inspector. By ju
Screenshot from 2023-07-07 13-13-43
st applying 400px (totally guessed that value) it made the popup even more usable:

**Comment by cienvaras** [comment]
@callinmullaney Are you sure that the styles are being correctly applied? Adding the `white-space: wrap` solved the issue for me without needing a `max-width`, because it allowed CKEditor to correctly calculate the dialog size. I don't see the word wrap applied in your screenshot.

**Comment by callinmullaney** [comment]
@cienvaras ok that helps. I think you mean `white-space: normal !important` instead of `white-space: wrap !important`. However, I am still seeing the popup slide off the screen at this smaller size. Verified your styles are being applied: 
Screenshot from 2023-07-07 14-53-56

Then when I added the max-width I get the following. Note: your `white-space: normal` styles coming through: 
Screenshot from 2023-07-07 14-49-52

**Comment by cienvaras** [comment]
@callinmullaney You are completely right, thanks! It's fixed now.

**Review by callinmullaney — APPROVED** [review]
:+1: looks good to me! Thanks @cienvaras

**Pull request merged**
